### ISSUE TITLE
一つ前のコメントを遡って読むことができない

### ISSUE THREAD

**Issue by yuya495** [CommentViewerCollection/MultiCommentViewer#113]
赤丸の部分で少し前のコメントを見ようとしても出来ませんでした
なお一つずつ下に進む場合は問題ありませんでした
![amarec(20190714-005957)](https://user-images.githubusercontent.com/8580180/61173901-4e7d6000-a5d4-11e9-8430-dc79159487c6.png)

**Comment by ryu-s** [comment]
スクロールバーが一番下か一番下に近い時にご指摘いただいた状態になるのですが、これは今のところ仕様です。他の不具合を解消するためにわざとやっています。

**Comment by yuya495** [comment]
了解です。
