### ISSUE TITLE
YouTubeで400エラーが出続ける

### ISSUE THREAD

**Issue by k0ta0uchi** [CommentViewerCollection/MultiCommentViewer#126]
表題のとおりです。
接続自体は出来るのですが、接続中400エラーが出続けます。
調査をお願いいたします。
![MultiCommentViewer_2019-10-25_13-10-49](https://user-images.githubusercontent.com/1085968/67544795-d0336c80-f731-11e9-8ac2-29f8a9a48ab2.png)

**Comment by ryu-s** [comment]
修正しました！単純なバグが原因でした。 1c96f8854d5e9e494c63f9749be018bb79852374

**Comment by k0ta0uchi** [comment]
迅速な対応ありがとうございます！！
