### ISSUE TITLE
リリース版でオプションの「表示する情報のレベル」が、再起動すると `Notice` になる。

### ISSUE THREAD

**Issue by ly-mg** [CommentViewerCollection/MultiCommentViewer#128]
表題の通りです。

ソースコードをざっとみたところ、`MultiCommentViewer.Test.DynamicOptionsTest.Init()` の中で、`ShowingInfoLevel` の箇所が `#if DEBUG` で分けられているので、これが該当するでしょうか。このコードは何を意図されたものですか？

**Comment by ryu-s** [comment]
すみません！バグなので修正しました！ 7d3577c5fc887168ce43b285fdc90707735f89d3
`#if DEBUG`に関しては以前デバッグ時に`DefaultValue=InfoType.Debug`にしていて、その名残です。。

**Comment by ly-mg** [comment]
なるほど理解しました。修正ありがとうございます。
