### ISSUE TITLE
コメントビュアーが機能しない

### ISSUE THREAD

**Issue by yuya495** [CommentViewerCollection/MultiCommentViewer#137]
Twitchの仕様が変わった為かコメビュが読み上げされません

**Comment by ryu-s** [comment]
試してみましたが、問題なく読み上げました。
使用しているバージョン、入力したURL、コメントの表示の可否などもう少し詳しく書いていただきたいです。

**Comment by yuya495** [comment]
すいません　チャンネルのＵＲＬじゃなくて　ダッシュボードのＵＲＬを入力してました　
チャンネルのＵＲＬを入力しなおしたらちゃんと読み上げされました。

**Comment by ryu-s** [comment]
了解です。
