### ISSUE TITLE
Twitchのコテハンが二重に読まれる

### ISSUE THREAD

**Issue by PRiMENON** [CommentViewerCollection/MultiCommentViewer#145]
Twitchで利用しています（開発ありがとうございます）。
同サイトで使用しますと、コテハンが二重に読み上げされてしまいます。
旧バージョンをさかのぼると v0.5.3では２回読み上げは起きませんでした。

* 再現する v0.5.8
* 再現しない v0.5.3

再現する環境
 * Windows 10 64bit
 * 棒読みちゃん BouyomiChan_0.1.11.0 Beta20

**Comment by ryu-s** [comment]
ご報告ありがとうございます！
以前、Twitchの"表示名"の表示に対応し、"表示名"の設定がある場合のユーザ名の表示を「表示名 (ユーザID)」とするように修正しました（ 979e26d01aa7be99feed3c6bc75283e6619aba1e ）。
この表示がそのままの形で棒読みちゃんに渡されてしまっていたために「表示名　ユーザID　コメント」と読まれてしまっていました。
先程修正した（ 577d620ef73cb8622a8c20982c0ff4cca559665d ）ので、次回のリリースに乗せようと思っています。
