### ISSUE TITLE
YouTubeライブチャットにおいて、上位チャットとすべてのチャットを切り替える方法について（アイデア）

### ISSUE THREAD

**Issue by taizan-hokuto** [CommentViewerCollection/MultiCommentViewer#147]
### YouTubeライブチャットにおいて、上位チャットとすべてのチャットを切り替える方法について（アイデア）

Youtubeのチャットページ（`https://www.youtube.com/live_chat?v={video_id}&is_popout=1`）をスクレイピングし、

「window["ytInitialData"] =」　以降のJSON（参照：[リポジトリ](https://github.com/CommentViewerCollection/MultiCommentViewer/blob/adba6535a41547e2a9d17137aaf363c901624f35/YouTubeLiveSitePluginTests/SampleData/LiveChat.txt#L37)）をextractした状態で、

- 上位チャット：

contents.liveChatRenderer.header.liveChatHeaderRenderer.viewSelector.sortFilterSubMenuRenderer.subMenuItems[0].continuation.reloadContinuationData.continuation

- すべてのチャット：

contents.liveChatRenderer.header.liveChatHeaderRenderer.viewSelector.sortFilterSubMenuRenderer.subMenuItems[1].continuation.reloadContinuationData.continuation

にそれぞれのcontinuationが格納されているので、これで切り替えられるのではないかと思います。

**Comment by ryu-s** [comment]
ありがとうございます！試してみたいと思います！
