### ISSUE TITLE
Chromeのencrypted_valueの暗号化方式が変わった

### ISSUE THREAD

**Issue by ryu-s** [CommentViewerCollection/MultiCommentViewer#150]
以前はDPAPIだったけど、v80からAES-256になったみたい。
chromiumがC++で書かれているけど、C#での正解が分からない。keyとかsaltに何を指定したらいいのやら。。。

**Comment by taizan-hokuto** [comment]
もうご存じかもしれませんが、AESで暗号化されたcookieの復号手順については下記のような感じになります。

https://qiita.com/taizan_hokuto/items/bff1a1ccd65655e1c386

鍵データ自体はDPAPIで復号するだけなので、それほど手間はないと思います。
あとはC#にAES_GCMのライブラリがあるかどうかですが・・・

**Comment by ryu-s** [comment]
ありがとうございます！
nonceまでは分かっていたのですが、keyが分からず困っていました。
明日か明後日辺りに試してみたいと思います。

**Comment by taizan-hokuto** [comment]
v0.5.13での修正対応の件、ありがとうございます。流石です。

**Comment by ryu-s** [comment]
こちらこそありがとうございました。本当に助かりました。
C#での実装方法が分からなかったので、取り急ぎRustで実装してみました。
因みにv0.5.12で対応済みです。
