### ISSUE TITLE
ニコニコ生放送で正常に接続されない

### ISSUE THREAD

**Issue by yuya495** [CommentViewerCollection/MultiCommentViewer#155]
自分の放送に接続しても放送タイトルなどなにも表示されない
棒読みちゃんもよみあげてくれません
ニコニコの仕様が変わったのかもしれません

**Comment by yuya495** [comment]
ちなみに仕様しているブラウザはＯｐｅｒａＧＸです
Twitchはちゃんと接続できます

**Comment by jesuissuyaa** [comment]
同様の現象が起きています（2020/11/11）
Twitch, Mirrativ は接続できています

**Comment by ryu-s** [comment]
ニコ生の仕様変更があったようで、未ログイン状態でのコメント取得ができなくなっていたので修正しました c57f2bd6fdfc531fed1e9eb3238bcc13f42fc140
