### ISSUE TITLE
YouTube でチャットメッセージのポーリング頻度が高すぎる

### ISSUE THREAD

**Issue by ly-mg** [CommentViewerCollection/MultiCommentViewer#167]
- YouTube で、チャットが流れていないとき、チャットサーバーにリクエストを送り続けています。

- ポーリング間隔をあけるなど、うまくできないものでしょうか？

- ユーザーのチャットが流れているときには、リクエストを送る頻度が下がるので、問題はなさそうです。

該当箇所:

`MultiCommentViewer\YouTubeLiveSitePlugin\Next\CommentProviderNext.cs`  
`ChatProvider2.ReceiveInternalAsync` メソッドの `while` ループ内  
`Tools.GetGetLiveChat` を呼び出している部分です。  

チャットが流れていないときは、ループ内で `Tools.GetGetLiveChat` を呼び出し続けています。

これが原因かどうかはわかりませんが、チャット頻度の低いチャンネルでは、数十分に一度程度、接続が切れることがあります。

該当箇所:

`MultiCommentViewer\YouTubeLiveSitePlugin\Next\Tools.cs`
`GetLiveChat.GetContinuation` メソッド内から `ChatUnavailableException` がスローされます。
サーバーから `500` や `503` エラーが返っています。

**Comment by ryu-s** [comment]
ありがとうございます！
サーバーから500とか503が来るのは完全にこれが原因ですね。。。
修正しました。 cc864086414b1e5ad004c35349cc004445a78f16
