### ISSUE TITLE
ニコ生で放送IDのみで接続するとエラーが発生する

### ISSUE THREAD

**Issue by mamireimu** [CommentViewerCollection/MultiCommentViewer#174]
Wikiにある[導入手順内の「有効なURLや放送IDの例」](https://github.com/CommentViewerCollection/MultiCommentViewer/wiki/%E5%B0%8E%E5%85%A5%E6%89%8B%E9%A0%86#%E6%9C%89%E5%8A%B9%E3%81%AAurl%E3%82%84%E6%94%BE%E9%80%81id%E3%81%AE%E4%BE%8B)通りに「lv(No)」のみで、接続すると「未対応の形式のURLが入力されました」と表示されて接続ができない

[確認済みバージョン]
v0.6.3(安定・ベータ共発生)

[SS]
![image](https://user-images.githubusercontent.com/19876392/124012945-abba8800-da1c-11eb-897f-1508c935cdef.png)

**Comment by ryu-s** [comment]
ありがとうございます！修正しました！
