### ISSUE TITLE
プルダウンメニューを接続しているサイトのみ表示してほしい

### ISSUE THREAD

**Issue by donokoanoko** [CommentViewerCollection/MultiCommentViewer#183]
コメントの送信先を選ぶプルダウンメニューが現状は登録しているサイトすべてが表示されますが、可能ならば接続ボタンを押したサイトのみ表示させるようにしてほしい。

**Comment by ryu-s** [comment]
確かに接続していないものは除くべきですね。
近日中に対応したいと思います。

**Comment by ryu-s** [comment]
実装完了しました d58ef9942c048db767c5abb8dfa22a8cbf94d76c
