### ISSUE TITLE
0.3.8にウィルス検出 @ Windows Defender

### ISSUE THREAD

**Issue by astrorobot110** [CommentViewerCollection/MultiCommentViewer#20]
トピックのとおりです。
現状バイナリでリリースされている0.3.6でウィルス検出されないので恐らく問題ないと思うのですが、アップデート時のファイルコピーの方法などに問題があるのかもしれません。

**Comment by ryu-s** [comment]
ご報告ありがとうございます。
こちらでもウイルススキャンをしてみましたが、ウイルスは検出されませんでした。私が配布しているものに関してはウイルスが混入している可能性はありません。どのようなウイルスが検出されたのでしょうか？可能であればスクリーンショットを撮って頂きたいです。
誤検知の可能性が高いと思われますが、第三者がウイルスを混入させた上で配布している可能性もありますので、v0.3.8のバイナリの入手方法を教えてください。マルチコメビュの自動アップデート機能によって以前のバージョンからアップデートしたものでしょうか？それともどこかのサイトからダウンロードしたものでしょうか？後者の場合はそのサイトのURLを教えていただきたいのと、ウイルスが検出されるバイナリが欲しいです。
また、誤検知であった場合、修正を検討したいと考えています。ただ、同様のご報告はこれまで一度も無いので、優先順位はやや低めになると思います。


>アップデート時のファイルコピーの方法などに問題があるのかもしれません

初期バージョンからアップデートに関するロジックには基本的に変更はありません。特にv0.3.6とv0.3.8は全く同じコードです。宜しければ、この部分に問題があるとお考えになった理由も教えて頂けないでしょうか？
