### ISSUE TITLE
Opera GX ブラウザにも対応してほしい

### ISSUE THREAD

**Issue by yuya495** [CommentViewerCollection/MultiCommentViewer#99]
Opera GX ブラウザにも対応してほしいです
![amarec(20190615-192655)](https://user-images.githubusercontent.com/8580180/59550292-e1aa8200-8fa3-11e9-862f-9cb65c065d4d.PNG)
![amarec(20190615-192319)](https://user-images.githubusercontent.com/8580180/59550296-e707cc80-8fa3-11e9-9148-396829e4f766.PNG)

**Comment by ryu-s** [comment]
対応完了です 6c3d44fa2d536c1d3fb2d59a7194cc0bc3d4e182
次回のリリースに乗せます
